####
# GitLab CI
####

# Image
image: ubuntu:24.04

# Stages
stages:
  - build
  - publish

# Build
Assemble:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
  # Packages
  - apt-get update && apt-get install -y build-essential git libgeoip-dev libgmp-dev zlib1g-dev libcurl4-gnutls-dev
  - mkdir -p dist/lib dist/include dist/include/stormlib dist/config
  # BNCSUtil (from Source)
  - apt-get install -y build-essential cmake
  - cd bncsutil/src/bncsutil
  - make && make install
  - cd $CI_PROJECT_DIR
  - cp /usr/lib/libbncsutil.so dist/lib
  - cp -R /usr/include/bncsutil dist/include
  # StormLib
  - apt-get install -y build-essential cmake zlib1g-dev libbz2-dev
  - cd StormLib
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_DYNAMIC_MODULE=1 ..
  - make && make install
  - cd $CI_PROJECT_DIR
  - cp /usr/local/lib/libstorm.a dist/lib
  - cp /usr/local/include/StormLib.h dist/include/stormlib
  - cp /usr/local/include/StormPort.h dist/include/stormlib
  # Aura
  - cp -R dist/include/* /usr/include # make dist/includes available for Aura build
  - make && make install
  - cp /usr/local/bin/aura* dist/bin/

