####
# GitLab CI
####

# Image
image: ubuntu:24.04

# Stages
stages:
  - build
  - publish

# Build
Assemble:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
  # Packages
  - apt-get update && apt-get install -y build-essential git libgeoip-dev libgmp-dev zlib1g-dev libcurl4-gnutls-dev cmake libbz2-dev
  - mkdir -p dist/bin-static dist/bin-shared
  - cd $CI_PROJECT_DIR
  # BNCSUtil (dynamic, .so)
  - apt-get install -y build-essential cmake
  - cd bncsutil/src/bncsutil
  - make && make install
  - cd $CI_PROJECT_DIR
  ## Shared library
  - cp /usr/lib/libbncsutil.so /usr/local/lib
  - cp /usr/lib/libbncsutil.so dist/bin-shared
  ## Header files
  ### - cp -R /usr/include/bncsutil dist/include
  # StormLib (shared, .so)
  - cd $CI_PROJECT_DIR
  - cd StormLib
  #- sed -i -e 's/option(BUILD_SHARED_LIBS "Compile shared libraries" OFF)/option(BUILD_SHARED_LIBS "Compile shared libraries" ON)/g' CMakeLists.txt
  - rm -rf build && mkdir -p build
  - cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1 ..
  - make && make install
  - cd $CI_PROJECT_DIR
  ## Shared library
  ### Already at /usr/local/lib
  ### - cp /usr/local/lib/libstorm.so /usr/local/lib
  - cp /usr/local/lib/libstorm.so dist/bin-shared
  ## Header files
  ### - cp /usr/local/include/StormLib.h dist/include/stormlib
  ### - cp /usr/local/include/StormPort.h dist/include/stormlib
  # MiniUPNP (shared, .so)
  - cd $CI_PROJECT_DIR
  - cd miniupnpc
  - make && make install
  - cd $CI_PROJECT_DIR
  ## Shared library
  - cp /usr/lib/libminiupnpc.so /usr/local/lib
  - cp /usr/lib/libminiupnpc.so dist/bin-shared
  # Aura (all shared libraries)
  - cd $CI_PROJECT_DIR
  - export AURADISABLEMINIUPNP="1"
  - export AURADISABLECPR="1"
  - make && make install
  - unset AURADISABLEMINIUPNP
  - unset AURADISABLECPR
  - touch /usr/bin/aura
  - mv /usr/bin/aura dist/bin-shared
  - chmod +x dist/bin-shared/aura
  ######################
  ### Static build     #
  ######################
  # StormLib (static, .a)
  - cd $CI_PROJECT_DIR
  - cd StormLib
  #- sed -i -e 's/option(BUILD_SHARED_LIBS "Compile shared libraries" ON)/option(BUILD_SHARED_LIBS "Compile shared libraries" OFF)/g' CMakeLists.txt
  - rm -rf build && mkdir -p build
  - cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
  - make clean && make && make install
  - cd $CI_PROJECT_DIR
  ## Static library
  ### Already at /usr/local/lib
  ### - cp /usr/local/lib/libstorm.a /usr/local/lib
  - cp /usr/local/lib/libstorm.a dist/bin-static
  ## Header files
  ### - cp /usr/local/include/StormLib.h dist/include/stormlib
  ### - cp /usr/local/include/StormPort.h dist/include/stormlib
  # MiniUPNP (static, .a)
  - cd $CI_PROJECT_DIR
  - cd miniupnpc
  - export CPPFLAGS="-DMINIUPNP_STATICLIB"
  - make clean && make && make install
  - unset CPPFLAGS
  - cd $CI_PROJECT_DIR
  ## Static library
  - cp /usr/lib/libminiupnpc.a /usr/local/lib
  - cp /usr/lib/libminiupnpc.a dist/bin-static
  ### - cp /usr/lib/libminiupnpc.a dist/lib
  # Aura (all static libraries)
  - cd $CI_PROJECT_DIR
  #- export AURADISABLEMINIUPNP="1"
  - export AURADISABLECPR="1"
  - export AURASTATIC="1"
  - make clean && make && make install
  - unset AURADISABLECPR
  - unset AURASTATIC
  - touch /usr/bin/aura
  - mv /usr/bin/aura dist/bin-static
  - chmod +x dist/bin-static/aura
