/*

  Copyright [2024] [Leonardo Julca]

  Permission is hereby granted, free of charge, to any person obtaining
  a copy of this software and associated documentation files (the
  "Software"), to deal in the Software without restriction, including
  without limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so, subject to
  the following conditions:

  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 */

#ifndef AURA_CONSTANTS_H_
#define AURA_CONSTANTS_H_

// includes.h

#define LOG_LEVEL_EMERGENCY 1
#define LOG_LEVEL_ALERT 2
#define LOG_LEVEL_CRITICAL 3
#define LOG_LEVEL_ERROR 4
#define LOG_LEVEL_WARNING 5
#define LOG_LEVEL_NOTICE 6
#define LOG_LEVEL_INFO 7
#define LOG_LEVEL_DEBUG 8
#define LOG_LEVEL_TRACE 9
#define LOG_LEVEL_TRACE2 10

#define ANTI_SPOOF_NONE 0
#define ANTI_SPOOF_BASIC 1
#define ANTI_SPOOF_EXTENDED 2
#define ANTI_SPOOF_FULL 3

// map.h

#define MAPSPEED_SLOW 1
#define MAPSPEED_NORMAL 2
#define MAPSPEED_FAST 3

#define MAPVIS_HIDETERRAIN 1
#define MAPVIS_EXPLORED 2
#define MAPVIS_ALWAYSVISIBLE 3
#define MAPVIS_DEFAULT 4

#define MAPOBS_NONE 1u
#define MAPOBS_ONDEFEAT 2u
#define MAPOBS_ALLOWED 3u
#define MAPOBS_REFEREES 4u

#define MAPFLAG_TEAMSTOGETHER 1
#define MAPFLAG_FIXEDTEAMS 2
#define MAPFLAG_UNITSHARE 4
#define MAPFLAG_RANDOMHERO 8
#define MAPFLAG_RANDOMRACES 16

#define MAPOPT_HIDEMINIMAP (1 << 0)
#define MAPOPT_MODIFYALLYPRIORITIES (1 << 1)
#define MAPOPT_MELEE (1 << 2) // the bot cares about this one...
#define MAPOPT_REVEALTERRAIN (1 << 4)
#define MAPOPT_FIXEDPLAYERSETTINGS (1 << 5) // and this one...
#define MAPOPT_CUSTOMFORCES (1 << 6)        // and this one, the rest don't affect the bot's logic
#define MAPOPT_CUSTOMTECHTREE (1 << 7)
#define MAPOPT_CUSTOMABILITIES (1 << 8)
#define MAPOPT_CUSTOMUPGRADES (1 << 9)
#define MAPOPT_WATERWAVESONCLIFFSHORES (1 << 11)
#define MAPOPT_HASTERRAINFOG (1 << 12)
#define MAPOPT_REQUIRESEXPANSION (1 << 13)
#define MAPOPT_ITEMCLASSIFICATION (1 << 14)
#define MAPOPT_WATERTINTING (1 << 15)
#define MAPOPT_ACCURATERANDOM (1 << 16)
#define MAPOPT_ABILITYSKINS (1 << 17)

#define MAPFILTER_MAKER_USER 1
#define MAPFILTER_MAKER_BLIZZARD 2

#define MAPFILTER_TYPE_MELEE 1
#define MAPFILTER_TYPE_SCENARIO 2

#define MAPFILTER_SIZE_SMALL 1
#define MAPFILTER_SIZE_MEDIUM 2
#define MAPFILTER_SIZE_LARGE 4

#define MAPFILTER_OBS_FULL 1
#define MAPFILTER_OBS_ONDEATH 2
#define MAPFILTER_OBS_NONE 4

#define MAPGAMETYPE_UNKNOWN0 (1) // always set except for saved games?
#define MAPGAMETYPE_BLIZZARD (1 << 3)
#define MAPGAMETYPE_MELEE (1 << 5)
#define MAPGAMETYPE_SAVEDGAME (1 << 9)
#define MAPGAMETYPE_PRIVATEGAME (1 << 11)
#define MAPGAMETYPE_MAKERUSER (1 << 13)
#define MAPGAMETYPE_MAKERBLIZZARD (1 << 14)
#define MAPGAMETYPE_TYPEMELEE (1 << 15)
#define MAPGAMETYPE_TYPESCENARIO (1 << 16)
#define MAPGAMETYPE_SIZESMALL (1 << 17)
#define MAPGAMETYPE_SIZEMEDIUM (1 << 18)
#define MAPGAMETYPE_SIZELARGE (1 << 19)
#define MAPGAMETYPE_OBSFULL (1 << 20)
#define MAPGAMETYPE_OBSONDEATH (1 << 21)
#define MAPGAMETYPE_OBSNONE (1 << 22)

#define MAPLAYOUT_ANY 0u
#define MAPLAYOUT_CUSTOM_FORCES 1u
#define MAPLAYOUT_FIXED_PLAYERS 3u

#define CACHE_REVALIDATION_NEVER 0
#define CACHE_REVALIDATION_ALWAYS 1
#define CACHE_REVALIDATION_MODIFIED 2

#define W3HMC_MODE_DISABLED 0
#define W3HMC_MODE_OPTIONAL 1
#define W3HMC_MODE_REQUIRED 2

// game.h
#define SLOTS_ALIGNMENT_CHANGED (1 << 0)
#define SLOTS_DOWNLOAD_PROGRESS_CHANGED (1 << 1)
#define SLOTS_HCL_INJECTED (1 << 2)

#define SAVE_ON_LEAVE_NEVER 0u
#define SAVE_ON_LEAVE_AUTO 1u
#define SAVE_ON_LEAVE_ALWAYS 2u

#define CUSTOM_LAYOUT_NONE 0u
#define CUSTOM_LAYOUT_ONE_VS_ALL 1u
#define CUSTOM_LAYOUT_HUMANS_VS_AI 2u
#define CUSTOM_LAYOUT_FFA 4u
#define CUSTOM_LAYOUT_DRAFT 8u
#define CUSTOM_LAYOUT_LOCKTEAMS 15u
#define CUSTOM_LAYOUT_COMPACT 16u
#define CUSTOM_LAYOUT_ISOPLAYERS 32u

#define REFRESH_PERIOD_MIN 10
#define REFRESH_PERIOD_MAX 500
#define LAG_TOLERANCE_MIN_TIME 100
#define LAG_TOLERANCE_MAX_TIME 2000
#define GAME_BANNABLE_MAX_HISTORY_SIZE 32

#define GAME_PAUSES_PER_PLAYER 3u
#define GAME_SAVES_PER_PLAYER 1u
#define GAME_SAVES_PER_REFEREE_ANTIABUSE 3u
#define GAME_SAVES_PER_REFEREE_DEFAULT 255u

#define GAME_ONGOING 0u
#define GAME_OVER_TRUSTED 1u
#define GAME_OVER_MMD 2u

#define HIDDEN_PLAYERS_NONE 0u
#define HIDDEN_PLAYERS_LOBBY 1u
#define HIDDEN_PLAYERS_GAME 2u
#define HIDDEN_PLAYERS_ALL 3u

#define HIGH_PING_KICK_DELAY 10000u
#define MAX_SCOPE_BANS 100u
#define AUTO_REHOST_COOLDOWN_TICKS 180000u

// gamesetup.h

#define SEARCH_TYPE_ONLY_MAP 1
#define SEARCH_TYPE_ONLY_CONFIG 2
#define SEARCH_TYPE_ONLY_FILE 3
#define SEARCH_TYPE_ANY 7

#define MATCH_TYPE_NONE 0u
#define MATCH_TYPE_MAP 1u
#define MATCH_TYPE_CONFIG 2u
#define MATCH_TYPE_INVALID 4u
#define MATCH_TYPE_FORBIDDEN 8u

#define RESOLUTION_OK 0
#define RESOLUTION_ERR 1
#define RESOLUTION_BAD_NAME 2

#define SETUP_USE_STANDARD_PATHS true
#define SETUP_PROTECT_ARBITRARY_TRAVERSAL false

#ifdef _WIN32
#define FILE_EXTENSIONS_MAP {L".w3x", L".w3m"}
#define FILE_EXTENSIONS_CONFIG {L".ini"}
#else
#define FILE_EXTENSIONS_MAP {".w3x", ".w3m"}
#define FILE_EXTENSIONS_CONFIG {".ini"}
#endif

#define GAMESETUP_ORIGIN_NONE 0
#define GAMESETUP_ORIGIN_GAME 1
#define GAMESETUP_ORIGIN_REALM 2
#define GAMESETUP_ORIGIN_IRC 3
#define GAMESETUP_ORIGIN_DISCORD 4
#define GAMESETUP_ORIGIN_INVALID 255

#define GAMESETUP_STEP_MAIN 0
#define GAMESETUP_STEP_RESOLUTION 1
#define GAMESETUP_STEP_SUGGESTIONS 2
#define GAMESETUP_STEP_DOWNLOAD 3

#define MAP_ONREADY_SET_ACTIVE 1
#define MAP_ONREADY_HOST 2
#define MAP_ONREADY_ALIAS 3

#define SUGGESTIONS_TIMEOUT 3000u
#define GAMESETUP_STALE_TICKS 180000u

// gameprotocol.h

#define W3GS_HEADER_CONSTANT 247
#define W3FW_HEADER_CONSTANT 249

#define GAME_NONE 0 // this case isn't part of the protocol, it's for internal use only
#define GAME_FULL 2
#define GAME_PUBLIC 16
#define GAME_PRIVATE 17

#define GAMETYPE_CUSTOM 1
#define GAMETYPE_BLIZZARD 9

#define PLAYERLEAVE_DISCONNECT 1
#define PLAYERLEAVE_LOST 7
#define PLAYERLEAVE_LOSTBUILDINGS 8
#define PLAYERLEAVE_WON 9
#define PLAYERLEAVE_DRAW 10
#define PLAYERLEAVE_OBSERVER 11
#define PLAYERLEAVE_LOBBY 13
#define PLAYERLEAVE_GPROXY 100

#define REJECTJOIN_FULL 9
#define REJECTJOIN_STARTED 10
#define REJECTJOIN_WRONGPASSWORD 27

#define ACTION_PAUSE 1u
#define ACTION_RESUME 2u
#define ACTION_SAVE 6u
#define ACTION_SAVE_ENDED 7u
#define ACTION_CHAT_TRIGGER 96u
#define ACTION_MODAL_BTN 106u
#define ACTION_SYNC_INT 107u

#define MAX_PLAYER_NAME_SIZE 15

#define CHAT_RECV_ALL 0
#define CHAT_RECV_ALLY 1
#define CHAT_RECV_OBS 2

// chat.h

#define FROM_GAME (1 << 0)
#define FROM_BNET (1 << 1)
#define FROM_IRC (1 << 2)
#define FROM_DISCORD (1 << 3)
#define FROM_OTHER (1 << 7)

#define CHAT_SEND_SOURCE_ALL (1 << 0)
#define CHAT_SEND_TARGET_ALL (1 << 1)
#define CHAT_LOG_CONSOLE (1 << 2)
#define CHAT_TYPE_INFO (1 << 3)
#define CHAT_TYPE_DONE (1 << 4)
#define CHAT_TYPE_ERROR (1 << 5)
#define CHAT_WRITE_TARGETS (CHAT_SEND_SOURCE_ALL | CHAT_SEND_TARGET_ALL | CHAT_LOG_CONSOLE)
#define CHAT_RESPONSE_TYPES (CHAT_TYPE_INFO | CHAT_TYPE_DONE | CHAT_TYPE_ERROR)

#define CHAT_ORIGIN_NONE 0
#define CHAT_ORIGIN_GAME 1
#define CHAT_ORIGIN_REALM 2
#define CHAT_ORIGIN_IRC 3
#define CHAT_ORIGIN_DISCORD 4
#define CHAT_ORIGIN_INVALID 255

#define USER_PERMISSIONS_GAME_PLAYER (1 << 0)
#define USER_PERMISSIONS_GAME_OWNER (1 << 1)
#define USER_PERMISSIONS_CHANNEL_VERIFIED (1 << 2)
#define USER_PERMISSIONS_CHANNEL_ADMIN (1 << 3)
#define USER_PERMISSIONS_CHANNEL_ROOTADMIN (1 << 4)
#define USER_PERMISSIONS_BOT_SUDO_SPOOFABLE (1 << 6)
#define USER_PERMISSIONS_BOT_SUDO_OK (1 << 7)

#define SET_USER_PERMISSIONS_ALL (0xFFFF)

#define COMMAND_TOKEN_MATCH_NONE 0
#define COMMAND_TOKEN_MATCH_PRIVATE 1
#define COMMAND_TOKEN_MATCH_BROADCAST 2

// config_realm.h

#define REALM_AUTH_PVPGN 0
#define REALM_AUTH_BATTLENET 1

#define COMMANDS_ALLOWED_NONE 0
#define COMMANDS_ALLOWED_UNVERIFIED 1
#define COMMANDS_ALLOWED_VERIFIED 2

// config_net.h 

#define MAP_TRANSFERS_NEVER 0
#define MAP_TRANSFERS_AUTOMATIC 1
#define MAP_TRANSFERS_MANUAL 2

// config_game.h

#define ON_DESYNC_NONE 0u
#define ON_DESYNC_NOTIFY 1u
#define ON_DESYNC_DROP 2u

#define ON_IPFLOOD_NONE 0u
#define ON_IPFLOOD_NOTIFY 1u
#define ON_IPFLOOD_DENY 2u

#define ON_UNSAFE_NAME_NONE 0u
#define ON_UNSAFE_NAME_CENSOR_MAY_DESYNC 1u
#define ON_UNSAFE_NAME_DENY 2u

#define READY_MODE_FAST 0u
#define READY_MODE_EXPECT_RACE 1u
#define READY_MODE_EXPLICIT 2u

#define HIDE_IGN_NEVER 0u
#define HIDE_IGN_HOST 1u
#define HIDE_IGN_ALWAYS 2u
#define HIDE_IGN_AUTO 3u

#define ON_ADV_ERROR_IGNORE_ERRORS 0u
#define ON_ADV_ERROR_EXIT_ON_MAIN_ERROR 1u
#define ON_ADV_ERROR_EXIT_ON_MAIN_ERROR_IF_EMPTY 2u
#define ON_ADV_ERROR_EXIT_ON_ANY_ERROR 3u
#define ON_ADV_ERROR_EXIT_ON_ANY_ERROR_IF_EMPTY 4u
#define ON_ADV_ERROR_EXIT_ON_MAX_ERRORS 5u

// config_discord.h

#define FILTER_ALLOW_ALL 0
#define FILTER_DENY_ALL 1
#define FILTER_ALLOW_LIST 2
#define FILTER_DENY_LIST 3

// config_commands.h

#define REALM_AUTH_PVPGN 0
#define REALM_AUTH_BATTLENET 1

#define COMMAND_PERMISSIONS_DISABLED 0
#define COMMAND_PERMISSIONS_SUDO 1
#define COMMAND_PERMISSIONS_SUDO_UNSAFE 2
#define COMMAND_PERMISSIONS_ROOTADMIN 3
#define COMMAND_PERMISSIONS_ADMIN 4
#define COMMAND_PERMISSIONS_VERIFIED_OWNER 5
#define COMMAND_PERMISSIONS_OWNER 6
#define COMMAND_PERMISSIONS_VERIFIED 7
#define COMMAND_PERMISSIONS_AUTO 8
#define COMMAND_PERMISSIONS_POTENTIAL_OWNER 9
#define COMMAND_PERMISSIONS_UNVERIFIED 10

#define COMMANDS_ALLOWED_NONE 0
#define COMMANDS_ALLOWED_UNVERIFIED 1
#define COMMANDS_ALLOWED_VERIFIED 2

#endif // AURA_CONSTANTS_H_
